using System;

namespace BankingAppMarch
{
    class Program
    {
        static void Main(string[] args)
        {
            /*
            var a1 = new Account();
            // a1.AccountNumber = 123456; //this needs to be autogenerated
            // a1.Balance = 10000000000000000; put the Setter to Private!!
            a1.EmailAddress = "test@test.com";
            a1.AccountType = "Checking";
            */

            var a1 = Bank.CreateAccount("test@test.com", "Chequeing", 0);

            Console.WriteLine($"AN: {a1.AccountNumber}, B: {a1.Balance}, CD: {a1.CreatedDate}, EA: {a1.EmailAddress}, AT: {a1.AccountType}");

            /*
            var a2 = new Account
            {
                EmailAddress = "2nd@test.com",
                AccountType = "Savings"
            }; // This is Object Initialization!!! Better performing code
            */

            var a2 = Bank.CreateAccount("test2@test.com", "SAvings", 100);

            Console.WriteLine($"AN: {a2.AccountNumber}, B: {a2.Balance}, CD: {a2.CreatedDate}, EA: {a2.EmailAddress}, AT: {a2.AccountType}");


        }
    }
}
